### PR TITLE
fix: add return types to functions

### PR DESCRIPTION
**Pull request by YuHyeonWook**
## Overview

Added return types to the 'assemble', 'combineCharacter', 'disassembleToGroups', 'getChoseong' functions to match the documentation and improve type safety

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/es-hangul/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

### CODE REVIEW

**Comment by okinawaa** [comment]
Of course, explicitly adding type in return statement to make them clear is beneficial. However, **editors like VSCode and Neovim can infer types within 100ms.**  Having to change the implementation and return types every time the function interface changes feels a bit inconvenient, so I don’t think this feature is really necessary. What do you think?

Let me know if you’d like any adjustments!

**Comment by YuHyeonWook** [comment]
Thank you for your feedback!! I understand your point. 
Just for reference, I was wondering in which case you explicitly add the return type.

**Comment by okinawaa** [comment]
I only explicitly declare the return type when I first declare the `function signature with an interface`. I don’t specify the return type in the function implementation.

**Comment by YuHyeonWook** [comment]
Thank you!!

**Pull request closed without merging**
